In [3]:
from scipy.linalg import svd
import numpy as np
# the original matrix
X=np.matrix([[1,1],[2,2],[-1,-1],[-2,-2],[1,-1],[-1,1]])

U,S,V=svd(X)


In [10]:
# analyzing the matrices
print("U shape is ",U.shape)
# Notice that S here is given as an array of singluar values and no as a matrix
print("S shape is",S.shape)
print("V shape is",V.shape)


U shape is  (6, 6)
S shape is (2,)
V shape is (2, 2)


In [13]:
# reconstuction of the original matrix
# 1. constucting the sigma matrix
m,n=6,2
sigma = np.zeros((m, n))
for i in range(min(m, n)):
    sigma[i, i] = S[i]
X2 = U@sigma@V
X2

array([[ 1.,  1.],
       [ 2.,  2.],
       [-1., -1.],
       [-2., -2.],
       [ 1., -1.],
       [-1.,  1.]])

In [14]:
# truncating the least important singular value
sigma

array([[4.47213595, 0.        ],
       [0.        , 2.        ],
       [0.        , 0.        ],
       [0.        , 0.        ],
       [0.        , 0.        ],
       [0.        , 0.        ]])

In [31]:
# so we drop the 2 
X_reduced=U@sigma[:,:1]@V[:1,:]
X_reduced

array([[ 1.00000000e+00,  1.00000000e+00],
       [ 2.00000000e+00,  2.00000000e+00],
       [-1.00000000e+00, -1.00000000e+00],
       [-2.00000000e+00, -2.00000000e+00],
       [ 2.12506581e-16,  2.12506581e-16],
       [-2.12506581e-16, -2.12506581e-16]])